---
- name: something
  hosts: localhost
  var_files:
    - key.yml

  tasks:
    - name: provision of ec2 instance on AWS.
      ec2:
        key_name: "ansiblekey"
        aws_access_key: "{{ myuser }}"
        aws_secret_key: "{{ mypass }}"
        instance_type: "t2.micro"
        image: ""
        wait: yes
        instance_tags:
          Name: webserver
        count: 3
        vpc_subnet_id: ""
        assign_public_ip: yes
        region: ""
        state: present
        group_id: ""

    - name: provision of ec2 instance on AWS.
      ec2:
        key_name: "ansiblekey"
        aws_access_key: "{{ myuser }}"
        aws_secret_key: "{{ mypass }}"
        instance_type: "t2.micro"
        image: ""
        wait: yes
        instance_tags:
          Name: loadbalancer
        count: 1
        vpc_subnet_id: ""
        assign_public_ip: yes
        region: ""
        state: present
        group_id: ""

---------------------

---
- name: webserver setup
  hosts: webservers
  tasks:
    - name: "Installing httpd software"
      package:
        name: "httpd"
        state: present

    - name: "Installing php software"
      package:
        name: "php"
        state: present

    - name: "Copying the web pages"
      copy:
        src: "index.php"
        dest: "/var/www/html/index.php"

    - name: "starting httpd service"
      service:
        name: "httpd"
        state: restarted

- name: LB-setup
  hosts: LB
  tasks:
    - name: "Installing haproxy"
      package:
        name: haproxy
        state: present
    - name: "Copying configuration file"
      template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

    - name: "Start service of haproxy"
      service:
        name: "haproxy"
        state: started
